import { Institution } from "@UVER/db/schema";

const IMAGE_URL =
  "https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2F4.bp.blogspot.com%2F-e9bUEPvkzbg%2FTha7GtBxj4I%2FAAAAAAAAI3k%2FQcgT3HpwUp8%2Fs1600%2FHarvard%252BUniversity%252BUSA%252BWallpapers%252Bby%252Bcool%252Bwallpapers%252B%2525281%252529.jpg&f=1&nofb=1&ipt=324cbffab4230b0ee657624527141f679f533a32767aacffc00d00d76f065f49";
const LOGO_URL =
  "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fstatic.vecteezy.com%2Fsystem%2Fresources%2Fpreviews%2F006%2F470%2F647%2Foriginal%2Funiversity-education-logo-design-template-free-vector.jpg&f=1&nofb=1&ipt=b127831a9eeb8bc218334ccb9bddccec5735f8322dfaafb35860c79a70c6d8de";

export const MOCK_DATA_INSTITUTIONS: Institution[] = [
  {
    id: "1",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: IMAGE_URL,
    logo: LOGO_URL,
    name: "University of Example",
    rating: 4.5,
    website: "https://example.com",
    address: "Los Angeles, California, 90089, United States",
    applicationDeadline: new Date("30.03.2026"),
    createdAt: new Date(),
    updatedAt: new Date(),
    majors: ["Computer Science", "Business Administration"],
    country: "United States",
    latitude: "34.052235",
    longitude: "-118.243683",
    city: "Los Angeles",
    degreeType: "Bachelor's",
    state: "California",
    tuitionPrice: "1000000",
    zipCode: "90089",
  },
  {
    id: "2",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: IMAGE_URL,
    logo: LOGO_URL,
    name: "University of Example",
    rating: 5,
    website: "https://example.com",
    address: "Los Angeles, California, 90089, United States",
    applicationDeadline: new Date("30.03.2026"),
    createdAt: new Date(),
    updatedAt: new Date(),
    majors: ["Computer Science", "Business Administration"],
    country: "United States",
    latitude: "34.052235",
    longitude: "-118.243683",
    city: "Los Angeles",
    degreeType: "Bachelor's",
    state: "California",
    tuitionPrice: "1000000",
    zipCode: "90089",
  },
  {
    id: "3",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: IMAGE_URL,
    logo: LOGO_URL,
    name: "University of Example",
    rating: 4,
    website: "https://example.com",
    address: "Los Angeles, California, 90089, United States",
    applicationDeadline: new Date("30.03.2026"),
    createdAt: new Date(),
    updatedAt: new Date(),
    majors: ["Computer Science", "Business Administration"],
    country: "United States",
    latitude: "34.052235",
    longitude: "-118.243683",
    city: "Los Angeles",
    degreeType: "Bachelor's",
    state: "California",
    tuitionPrice: "1000000",
    zipCode: "90089",
  },
  {
    id: "4",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: IMAGE_URL,
    logo: LOGO_URL,
    name: "University of Example",
    rating: 3,
    website: "https://example.com",
    address: "Los Angeles, California, 90089, United States",
    applicationDeadline: new Date("30.03.2026"),
    createdAt: new Date(),
    updatedAt: new Date(),
    majors: ["Computer Science", "Business Administration"],
    country: "United States",
    latitude: "34.052235",
    longitude: "-118.243683",
    city: "Los Angeles",
    degreeType: "Bachelor's",
    state: "California",
    tuitionPrice: "1000000",
    zipCode: "90089",
  },
  {
    id: "5",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    image: IMAGE_URL,
    logo: LOGO_URL,
    name: "University of Example",
    rating: 2,
    website: "https://example.com",
    address: "Los Angeles, California, 90089, United States",
    applicationDeadline: new Date("30.03.2026"),
    createdAt: new Date(),
    updatedAt: new Date(),
    majors: ["Computer Science", "Business Administration"],
    country: "United States",
    latitude: "34.052235",
    longitude: "-118.243683",
    city: "Los Angeles",
    degreeType: "Bachelor's",
    state: "California",
    tuitionPrice: "1000000",
    zipCode: "90089",
  },
];

export const CHIPS_MAJORS = [
  {
    label: "📒 Accounting",
    active: true,
  },
  {
    label: "📐 Architecture",
    active: false,
  },
  {
    label: "🎨 Art",
    active: false,
  },
  {
    label: "🍥 Design",
    active: false,
  },
  {
    label: "👔 Business",
    active: false,
  },
];
